config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root "messages#index"

  resources :messages do
     resources :comments
  end

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :message
  belongs_to :user
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :messages
  has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  before_action :find_message
  before_action :find_comment, only: [:edit, :update, :destroy]


  def create
    @comment = @message.comments.create(comment_params)
    @comment.user_id = current_user.id

    if @comment.save
      redirect_to message_path(@message)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @comment.update(comment_params)
      redirect_to message_path(@message)
    else
      render 'edit'
    end
  end

  def destroy
    @comment.destroy
    redirect_to message_path(@message)
  end


  private

    def comment_params
      params.require(:comment).permit(:content)
    end

    def find_message
      @message = Message.find(params[:message_id])
    end

    def find_comment
      @comment = @message.comments.find(params[:id])
    end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def my_message  
  end

  def show
  end

  def new
    @message = current_user.messages.build
  end

  def create
    @message = current_user.messages.build(message_params)
    if @message.save
      redirect_to root_path
    else
      redirect_to new_message_path
    end
  end

  def edit
  end

  def update
    if @message.update(message_params)
      redirect_to message_path
    else
      render 'edit'
    end
  end

  def destroy
    @message.destroy
    redirect_to root_path
  end


  private
    def message_params
      params.require(:message).permit(:title, :description)
    end
    def find_message
      @message = Message.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coments_helper.rb
module ComentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/comments/_comment.html.erb
<p><%= comment.content %></p>
<p>Posted by : <%= comment.user.email %> ,
<%= time_ago_in_words(comment.created_at) %> ago</p>

<% if user_signed_in? %>
  <% if comment.user_id == current_user.id  %>
     <%= link_to 'Edit', edit_message_comment_path(comment.message, comment) %>
     <%= link_to 'Delete', message_comment_path(comment.message, comment),method: :delete,
       data: {confirm: "Are you shure?"} %>
  <% elsif @message.user_id == current_user.id  %>
    <%= link_to 'Delete', message_comment_path(comment.message, comment),method: :delete,
        data: {confirm: "Are you shure?"} %>
  <% end %>
<% end %>

<hr />

app/views/comments/_form.html.erb
<%= simple_form_for([@message, @message.comments.build]) do |f| %>
  <%= f.input :content, label: "Comment"  %>
  <%= f.button :submit %>
<% end %>

app/views/comments/edit.html.erb
<h3>Edit Comment</h3>
<%= simple_form_for([@message, @comment]) do |f| %>
  <%= f.input :content, label: 'Comment'  %>
  <%= f.button :submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MassageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <%= link_to "LET`S TALK ", root_path, class: "navbar-brand" %>
    </div>
    <ul class="nav navbar-nav">
      <li><%= link_to "All Massage ", root_path %></li>

     <% if user_signed_in? %>
         <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"
            role="button" aria-haspopup="true" aria-expanded="false">My Profile<span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><%= link_to "My Messages", messages_path %></li>
              <li><a href="#">My Freinds</a></li>
              <li><a href="#">My Chat</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Prifile Settings</a></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "SignOut", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
      <% else %>
           <li><%= link_to "SignUp", new_user_registration_path %></li>
           <li><%= link_to "LogIn", new_user_session_path %></li>
      <% end %>
    </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

    <% if user_signed_in? %>
    <li><%= link_to "Create New Message", new_message_path, class: "navbar-text navbar-right navbar-link" %></li>
    <% end %>
  </div>
</div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "New Title" %>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit Pages</h1>
<br />
<%= render 'form' %>
<%= link_to 'back', root_path%>

app/views/messages/index.html.erb
<h1>All Messages</h1>
<p>© <%= Date.today.year %> Let`s Talk About ...</p>
<% if user_signed_in? %>
  <p><%= current_user.email %></p>
<% end %>
<br />
<div class="col-md-6 col-md-offset-2">
    <% @messages.each do |message| %>
    <h3><%= message.title %></h3>
    <br />
    <%= link_to "Detals", message_path(message), class: "btn btn-default"  %>
    <% end %>
    <br /><hr />
    <%= link_to "New Message", new_message_path %>
</div>

app/views/messages/my_message.html.erb
<h1>My Messages</h1>

app/views/messages/my_messages.html.erb
<h1>All Messages</h1>
<br />
<% @messages.each do |message| %>
<h3><%= message.title %></h3>
<br />
<%= link_to "Detals", message_path(message), class: "btn btn-default"  %>
<% end %>
<br /><hr />
<%= link_to "New Message", new_message_path %>

app/views/messages/new.html.erb
<h1>NEW Pages</h1>
<%= render 'form' %>
<%= link_to 'back', root_path%>

app/views/messages/show.html.erb
<h1>SHOW Pages</h1>
<h3><%= @message.title %></h3>
<p>Posted by: <%= @message.user.email %></p></ br>
<p>Time ago: <%= time_ago_in_words(@message.created_at) %> ago</p>
<h5><%= @message.description %></h5>

<% if user_signed_in? %>
  <% if @message.user_id == current_user.id %>
    <%= link_to 'Edit Message', edit_message_path(@message) %>
    <%= link_to 'Delete Message', message_path(@message), method: :delete, data: {confirm: "Are ypu shure"} %>
  <% end %>
<% end %>

<br />
<h3>Comment</h3>
<%= render @message.comments %>

<h3>Replay Comment</h3>
<%= render 'comments/form' %>

<br /><br /><hr />
<%= link_to 'back', root_path %>